name: Planet-Workflow-02
on: push

jobs: 
    job-01:
        runs-on: ubuntu-22.04
        steps:
            - name: Hello-Earth
              run: echo "Hello-Earth"

    job-02:
        runs-on: ubuntu-22.04
        needs: job-01
        steps:
            - name: Hellow-World
              run: echo "Hello-World"



    job-03:
        runs-on: ubuntu-22.04
        needs: job-02
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: run-ascii-script
              run: |
                 sudo chmod 777 ascii.sh
                 ./ascii.sh

